# Generated by Django 3.1 on 2020-08-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotionData',
            fields=[
                ('time', models.FloatField(default=0, primary_key=True, serialize=False)),
                ('imuA1', models.FloatField(blank=True, null=True)),
                ('imuA2', models.FloatField(blank=True, null=True)),
                ('imuA3', models.FloatField(blank=True, null=True)),
                ('imuG1', models.FloatField(blank=True, null=True)),
                ('imuG2', models.FloatField(blank=True, null=True)),
                ('imuG3', models.FloatField(blank=True, null=True)),
                ('imuM1', models.FloatField(blank=True, null=True)),
                ('imuM2', models.FloatField(blank=True, null=True)),
                ('imuM3', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OceanData',
            fields=[
                ('time', models.FloatField(default=0, primary_key=True, serialize=False)),
                ('temp1', models.FloatField(blank=True, null=True)),
                ('calibratedTemp1', models.FloatField(blank=True, null=True)),
                ('temp1Stable', models.FloatField(blank=True, null=True)),
                ('temp2', models.FloatField(blank=True, null=True)),
                ('calibratedTemp2', models.FloatField(blank=True, null=True)),
                ('temp2Stable', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
