# Generated by Django 3.1 on 2020-08-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('CDIP_buoy', models.CharField(max_length=3)),
                ('CDIP_height', models.FloatField(blank=True, null=True)),
                ('CDIP_temp', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
