# Generated by Django 3.1 on 2020-08-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='motion_data',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='ride',
            name='ocean_data',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
