# Generated by Django 3.1 on 2020-08-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideData',
            fields=[
                ('rideId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('startTime', models.CharField(blank=True, max_length=20, null=True)),
                ('endTime', models.CharField(blank=True, max_length=20, null=True)),
                ('buoyCDIP', models.CharField(max_length=3)),
                ('heightCDIP', models.FloatField(blank=True, null=True)),
                ('tempCDIP', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=10, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
