# Generated by Django 3.1 on 2020-08-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_auto_20200820_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
