# Generated by Django 3.1 on 2020-08-22 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_ridedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='motiondata',
            name='ride',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ride.ridedata'),
        ),
        migrations.AddField(
            model_name='oceandata',
            name='ride',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ride.ridedata'),
        ),
    ]
