# Generated by Django 3.1 on 2020-08-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_auto_20200822_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motiondata',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='oceandata',
            name='ride',
        ),
        migrations.AddField(
            model_name='motiondata',
            name='rideId',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='oceandata',
            name='rideId',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
