# Generated by Django 3.1 on 2020-08-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_auto_20200822_0437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MotionData',
        ),
        migrations.DeleteModel(
            name='OceanData',
        ),
    ]
