# Generated by Django 3.1 on 2020-08-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0007_auto_20200824_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridedata',
            name='heightListSmartfin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridedata',
            name='tempListSmartfin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
