# Generated by Django 3.1 on 2020-08-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0009_auto_20200825_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridedata',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ridedata',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
