# Generated by Django 3.1 on 2020-09-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0012_buoys'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridedata',
            name='motionData',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridedata',
            name='oceanData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
